# Generated by Django 3.0.7 on 2021-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=800)),
                ('image', models.FileField(default='image', upload_to='Images')),
                ('minimum_price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
