# Generated by Django 3.0.7 on 2021-04-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bidStartDate', models.DateTimeField()),
                ('bidEndDate', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
            ],
            options={
                'db_table': 'Auction',
            },
        ),
    ]
