# Generated by Django 3.0.7 on 2021-04-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.FileField(default='image', upload_to='Images'),
        ),
    ]
