# Generated by Django 3.0.7 on 2021-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auctionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='bidEndDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bidStartDate',
            field=models.DateTimeField(null=True),
        ),
    ]
