# Generated by Django 3.0.7 on 2021-04-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20210402_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('bid_amount', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Buyer',
            },
        ),
    ]
