# Generated by Django 3.0.7 on 2021-04-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='bid_amount',
        ),
    ]
