# Generated by Django 3.0.7 on 2021-04-02 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_buyer_bid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bidEndDate',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bidStartDate',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
        migrations.AddField(
            model_name='auction',
            name='bidding_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Auction1',
            fields=[
                ('auction_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('bidding_amount', models.PositiveIntegerField(null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Buyer')),
            ],
            options={
                'db_table': 'Auction_1',
            },
        ),
    ]
