# Generated by Django 3.0.7 on 2021-04-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20210402_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auctionStatus',
        ),
    ]
