# Generated by Django 3.0.7 on 2021-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_remove_product_auctionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=800)),
                ('image', models.FileField(default='image', upload_to='Images')),
                ('minimum_price', models.PositiveIntegerField()),
                ('bidStartDate', models.DateTimeField(null=True)),
                ('bidEndDate', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Product_1',
            },
        ),
    ]
