# Generated by Django 3.0.7 on 2021-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_product1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bidEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bidStartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
